# Generated by Django 2.0.1 on 2018-01-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180122_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.FloatField(),
        ),
    ]
