# Generated by Django 2.0.1 on 2018-01-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('about_site', models.TextField()),
                ('imageURL', models.CharField(max_length=300)),
            ],
        ),
    ]
